export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: 'category/FETCHCATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'category/FETCHCATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'category/FETCHCATEGORIES_FAILED',
};